-- Oracle
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE 
FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B
WHERE A.BOARD_ID = B.BOARD_ID AND TO_CHAR(A.CREATED_DATE, 'YYYY-MM') = '2022-10'
ORDER BY CREATED_DATE, TITLE;

-- SELECT문에 AS는 생략이 가능하다
-- ORDER BY의 default는 ASC이다
-- 처음에 JOIN ON으로 풀려고 했으나 WHERE 조건문으로 충분히 조건에 맞는 데이터 추출이 가능했다